<?php

/**
 * @file
 * This file provides log/backtrace functionality when cache_flush is called.
 */

/**
 * Implements hook_cache_flush().
 */
function flush_trace_cache_flush() {
  $message = 'Cache flush triggered';
  // Set parameters in debug_backtrace() as necessary to avoid OOM errors.
  $backtrace = debug_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS, 10);
  $trace = print_r($backtrace, TRUE);
  $variables = [
    '%type' => 'flush_trace',
    '@message' => $message,
    '%backtrace_string' => $trace,
  ];
  \Drupal::logger('flush_trace')->debug('%type: @message in %backtrace_string', $variables);
}
